// Self-host the Latin subset of Libre Franklin (chrome) + Spline Sans Mono (data
// labels) as woff2. Fetches the Google Fonts CSS with a modern UA (yields woff2),
// keeps only the `/* latin */` subset blocks, downloads them to public/fonts/, and
// writes src/styles/fonts.css. Run once locally: `npm run fonts`. Output committed.

import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const FONT_DIR = join(ROOT, 'public', 'fonts');

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Libre+Franklin:wght@400;500;600&family=Spline+Sans+Mono:wght@400;500&display=swap';

function slug(family: string): string {
  return family.toLowerCase().replace(/\s+/g, '-');
}

async function main() {
  await mkdir(FONT_DIR, { recursive: true });
  const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => r.text());

  // split into (comment, @font-face) pairs; keep only latin subset
  const blocks = css.split('/*').slice(1); // each starts "subset */ @font-face {...}"
  const faces: string[] = [];
  for (const b of blocks) {
    const subset = b.slice(0, b.indexOf('*/')).trim();
    if (subset !== 'latin') continue;
    const family = /font-family:\s*'([^']+)'/.exec(b)?.[1];
    const weight = /font-weight:\s*(\d+)/.exec(b)?.[1];
    const url = /src:\s*url\(([^)]+)\)/.exec(b)?.[1];
    if (!family || !weight || !url) continue;
    const file = `${slug(family)}-${weight}.woff2`;
    const bytes = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    await writeFile(join(FONT_DIR, file), bytes);
    console.log(`  ${file}  ${(bytes.length / 1024).toFixed(1)}KB`);
    faces.push(
      `@font-face {\n` +
      `  font-family: '${family}';\n` +
      `  font-style: normal;\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('/fonts/${file}') format('woff2');\n` +
      `  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+2010-2027, U+2030-205E, U+2074, U+20AC, U+2122, U+2212;\n` +
      `}`,
    );
  }
  const out = `/* Generated by pipeline/src/fonts.ts — self-hosted Latin subsets. Do not edit by hand. */\n${faces.join('\n')}\n`;
  await writeFile(join(ROOT, 'src', 'styles', 'fonts.css'), out);
  console.log(`wrote src/styles/fonts.css (${faces.length} faces)`);
}

main().catch((e) => { console.error(e); process.exit(1); });
